[BASE_INFO]
# The app name will be applied to all processes including agent service integration.
appname = 'demo_app'

[CORE_PACKAGE]
# Perform a full component scan and registration for all the paths under this list.
default = ['sample_standard_app.intelligence.agentic']
# Scan and register agent components for all paths under this list, with priority over the default.
agent = ['sample_standard_app.intelligence.agentic.agent']
# Scan and register knowledge components for all paths under this list, with priority over the default.
knowledge = ['sample_standard_app.intelligence.agentic.knowledge']
# Scan and register llm components for all paths under this list, with priority over the default.
llm = ['sample_standard_app.intelligence.agentic.llm']
# Scan and register planner components for all paths under this list, with priority over the default.
planner = []
# Scan and register tool components for all paths under this list, with priority over the default.
tool = ['sample_standard_app.intelligence.agentic.tool']
# Scan and register memory components for all paths under this list, with priority over the default.
memory = ['sample_standard_app.intelligence.agentic.memory']
# Scan and register service components for all paths under this list, with priority over the default.
service = ['sample_standard_app.intelligence.service.agent_service']
# Scan and register prompt components for all paths under this list, with priority over the default.
prompt = ['sample_standard_app.intelligence.agentic.prompt']
# Scan and register product components for all paths under this list, with priority over the default.
product = ['sample_standard_app.platform.difizen.product']
# Scan and register workflow components for all paths under this list, with priority over the default.
workflow = ['sample_standard_app.platform.difizen.workflow']
# Scan and register store components for all paths under this list, with priority over the default.
store = ['sample_standard_app.intelligence.agentic.knowledge.store']
# Scan and register rag_router components for all paths under this list, with priority over the default.
rag_router = ['sample_standard_app.intelligence.agentic.knowledge.rag_router']
# Scan and register doc_processor components for all paths under this list, with priority over the default.
doc_processor = ['sample_standard_app.intelligence.agentic.knowledge.doc_processor']
# Scan and register query_paraphraser components for all paths under this list, with priority over the default.
query_paraphraser = ['sample_standard_app.intelligence.agentic.knowledge.query_paraphraser']
# Scan and register memory_compressor components for all paths under this list, with priority over the default.
memory_compressor = ['sample_standard_app.intelligence.agentic.memory.memory_compressor']
# Scan and register memory_storage components for all paths under this list, with priority over the default.
memory_storage = ['sample_standard_app.intelligence.agentic.memory.memory_storage']
# Scan and register log_sink components for all paths under this list, with priority over the default.
log_sink = ['sample_standard_app.intelligence.utils.log_sink']

[SUB_CONFIG_PATH]
# Log config file path, an absolute path or a relative path based on the dir where the current config file is located.
log_config_path = './log_config.toml'
# Custom key file path, use to save your own secret key like open ai or sth else. REMEMBER TO ADD IT TO .gitignore.
custom_key_path = './custom_key.toml'

[DB]
# A sqlalchemy db uri used for storing various info, for example, service request, generated during application running.
# If it's empty, agentUniverse will create a local sqlite db as default choice.
system_db_uri = ''

[GUNICORN]
# Use gunicorn as http server when activate is 'true', or only use flask.
activate = 'false'
# Gunicorn config file path, an absolute path or a relative path based on the dir where the current config file is located.
gunicorn_config_path = './gunicorn_config.toml'

[GRPC]
activate = 'false'
max_workers = 10
server_port = 50051

[MONITOR]
activate = false
dir = './monitor'
